server:
  port: 80
spring:
  application:
    name: cloud-order-service

eureka:
  client:
    #false表示不向注册中心注册自己
    register-with-eureka: true
    #是否从eurekaserver抓取已有的注册信息，默认true,单节点无所谓，集群必须设置true 才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/
