server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的id没有固定规则但要求唯一
         # uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #路由的id没有固定规则但要求唯一
          #uri: http://localhost:8001 #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            - Cookie=username,zzyy
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      #false表示不向注册中心注册自己
      register-with-eureka: true
      #是否从eurekaserver抓取已有的注册信息，默认true,单节点无所谓，集群必须设置true 才能配合ribbon使用负载均衡
      fetch-registry: true
      #设置与eureka server交互的地址查询服务和注册服务都需要依赖这个地址
      defaultZone: http://eureka7001.com:7001/eureka
